#!/bin/bash
read -p "Install media codecs (y/n)?"
if [ "$REPLY" != "y" ]
        then
                exit
fi
apt-get install debian-keyring

if [[ -z $(grep "deb http://mirror.optus.net/debian-multimedia/ stable main" /etc/apt/sources.list) ]]
        then
                echo deb http://mirror.optus.net/debian-multimedia/ stable main >> /etc/apt/sources.list
                echo Added to List
fi

gpg --keyring /usr/share/keyrings/debian-keyring.gpg -a --export 07DC563D1F41B907 |apt-key add -
apt-get update
apt-get upgrade
apt-get install w64codecs  --force-yes
apt-get install lame --force-yes
apt-get install libdvdcss2 --force-yes
apt-get install libavcodec-extra-52  --force-yes
apt-get install gstreamer0.10-lame --force-yes
